create table public.reminders (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  contest_name text not null,
  start_time text not null
);

-- Optional: Add Row Level Security (RLS) policies if needed. 
-- By default, if RLS is not enabled, anyone with the API key can read/write.
-- To be safe, let's enable RLS and allow anonymous access for your bot
-- (assuming your bot uses the anon key and you want it to have full access).
alter table public.reminders enable row level security;

create policy "Allow all actions for anon users on reminders"
  on public.reminders
  for all
  using (true)
  with check (true);
